attributes:
    dotfiles:
    git:
        name: Damon Petta
        email: d@petta.org
    osxdefaults:
        computername: damon-air
    authorization:
        sudo:
            users:
                - damon
            passwordless: true
            include_sudoers_d: true
