recipes:
    global:
        - dotfiles::gitconfig
        - applications::ssh_config
        - dotfiles::vim
        - dotfiles::workspace
    mac_os_x:
        - applications::sublime_text_3
        - applications::gnu-tar
attributes:
    homebrewalt:
        apps:
            - git
            - git-extras
            - irssi
            - autoconf
            - automake
            - redis
            - unrar
            - android-sdk
            - astyle
            - autossh
            - bazaar
            - casperjs
            - chromedriver
            - git
            - gnupg
            - go
            - heroku-toolbelt
            - wget
            - pwgen
            - xmlstarlet
            - htop-osx
            - git-flow
            - siege
            - watch
            - rsync
            - mongodb
            - elasticsearch

    nodejs:
        apps:
            - uglify-js
            - uglifycss
            - bower
            - grunt
            - grunt-cli
    gems:
        - sass
        - git-up
        - kstrano
        - deliver
        - crafter
